### ISSUE TITLE
Give contributors more rights, releasers less

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/github-tools#3]
### Subject of the feature

on May 23, GitHub introduced two new roles for people in teams on repos. Triage and maintain: https://github.com/unifiedjs/governance/issues/18.

### Extra

We structure our GitHub access by team:
- Every repo is added to every team with a team-specific role. Take for example the mergers team: every repo in the org is in the mergers team with the `write` role
- Members are added to teams. For example, if someone’s on the mergers team, they therefore get the `write` role on each repo

One aspect of this is that it’s easy to see who has what roles. You can ping `@unifiedjs/mergers` and know that these people have write rights.

### Problem

- Problem a): there are new roles, we should use them
- Problem b): emeriti (and in the future, contributors, https://github.com/unifiedjs/rfcs/pull/2) have read rights, which is the same as non-members. That doesn’t give a lot of ownership.
- Problem c) releasers have admin rights (superpowers): they can perform destructive actions (deleting repos)

### Expected behaviour

I suggest:

- Readers (currently emeriti, future contributors) to become triagers.
  This will allow them to perform the following actions:
  - Apply labels
  - Close, reopen, and assign all issues and pull requests
- Releasers to become maintainers.
  This will prevent them from performing the following actions (emphasis mine):
  - Delete an issue
  - Merge pull requests on protected branches, even if there are no approving reviews
  - Define code owners for a repository
  - Create and edit repository social cards
  - Add a repository to a team
  - **Manage outside collaborator access to a repository**
  - Limit interactions with a repository
  - Change a repository's visibility
  - Make a repository a template
  - Change a repository's settings
  - **Manage team and collaborator access to the repository**
  - Edit the repository's default branch
  - Manage webhooks, service hooks, and deploy keys
  - Enable the dependency graph for a private repository
  - Receive security alerts for vulnerable dependencies in a repository
  - Designate additional people or teams to receive security alerts for vulnerable dependencies
  - Opt in to data use for a private repository
  - Create maintainer security advisories
  - Allow or disable forks for a specific private repository
  - Transfer repositories into the organization
  - **Delete or transfer repositories out of the organization**
  - Archive repositories
  - Display a sponsor button

### Considerations

I do not see any downside of giving readers access to these two new actions. It only gives more of a sense of ownership.

The downside of downgrading releasers is that it becomes harder to perform certain actions, as someone else needs to be asked to e.g. delete an issue. I think that’s fine though, and is a more secure and visible process as two people are involved and someone signs off on the change.

Another downside is that there’s not much of a difference between mergers and releasers anymore. I don’t think that’s a problem, because that difference is now in access on npm (read-only vs read-write). So the names are more apt (mergers vs releasers better explains their access).

Note that the core team (and by extension the team lead, as they are a core member) can always perform these admin actions. Core members are also *owners* of whole organisations, giving them [even more power](https://help.github.com/en/articles/permission-levels-for-an-organization#permission-levels-for-an-organization).

Alternatively, we can split “releasers” into maintainers and admins. I think that’s typically superfluous to have so many teams because we typically don’t have too many members.

/cc @unifiedjs/core

**Comment by wooorm** [comment]
@unifiedjs/core Ping! I’d appreciate your thoughts

**Comment by ChristianMurphy** [comment]
> This will prevent them from performing the following actions (emphasis mine):

would releasers loose all the permissions listed or just the highlighted ones?

**Comment by wooorm** [comment]
The emphasis was used to highlight the IMO most important ones.
They would all the listed permissions.

- I think it’ll make these things a bit slower
- I can think of ways that almost all these rights can be misused (except showing a sponsor button maybe haha)
- What makes it a bit more dangerous, is that there’s no notification for when someone e.g., deletes a repo or changes a branch, so involving two people enhances visibility of these actions.

**Comment by johno** [comment]
This sgtm!

I wouldn't worry about splitting releasers into maintainers/admins, we have enough teams for now I think. We can always split things up later if we find we need more granularity.

**Comment by ChristianMurphy** [comment]
SGTM as well
