### ISSUE TITLE
GitHub labels

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/github-tools#4]
# Issue

### Subject of the feature

We need unified labels so that to streamline issue handling across the collective.

### Problem

The GitHub label defaults are broad and not very useful. With tooling it becomes easier to automate labels. We can benefit from that.

### Expected behaviour

I propose the labels posted in the following comment. I got them by looking at electron/electron’s labels, MDX, unifiedjs/unified, remarkjs/remark, and recent issues across the collective.

These labels are scoped with a prefix to group them together and add a bit more context.

After these labels are added, we can streamline the triage process as well. For inspiration, see [Electron’s triage process guide](https://github.com/electron/governance/blob/master/playbooks/issue-triage.md#process).

### Questions

- Are these labels useful and usable?
- Are there other labels needed?
- Suggestions on my emoji game? 😏

/cc @unifiedjs/core

**Comment by wooorm** [comment]
# Proposal

#### Status

Status labels can be used to review the current work log with a GitHub search.  Issues and PRs should have exactly one `status` label.

* `🔍 status/open` - Newly reported bug or proposed feature
  The issue is open
* `🙆 status/confirmed` - A member reproduced the bug or agreed with the feature
  The issue is open and confirmed
* `🚫 status/wontfix`
  This is not (enough of) an issue
* `🥂 status/merged`
  The issue is solved
* `⛵️ status/released`
  The issue is released

#### Blocked

Open and confirmed issues can be blocked from progressing:

* `🌊 blocked/upstream`
  The issue cannot progress till work is done somewhere else
* `🗳 blocked/vote`
  The issue cannot progress till further comments
* `🛠 blocked/wip`
  The issue is being worked on

#### SemVer

Issues that affect the interface (API, CLI, input, output) must have exactly one `semver` label.

* `👶 semver/patch` - Backwards-compatible fixes
* `🧒 semver/minor` - Backwards-compatible functionality
* `🧑 semver/major` - Incompatible changes

#### Type of issue

There are different types of issues.

* `📣 type/announcement`
* `💬 type/discussion`
* `🙋 type/question`
* `🐛 type/bug`
* `🦋 type/enhancement`

#### Area of issue

Issues affect different areas.

* `📦 area/dependencies`
* `📚 area/docs`
* `👀 area/external`
* `🗄 area/interface`
* `🏁 area/performance`
* `🔒 area/security`
* `🕸️ area/test`
* `🏗 area/tools`
* `☂️ area/types`

#### Affected platform

Some issues affect a certain platform.

* `🌐 platform/browser`
* `🐢 platform/node`
* `🐧 platform/linux`
* `🍏 platform/macos`
* `📎 platform/windows`

#### Other

Good first issues can be created as “bait” for potential contributors.
Help wanted signals a) opinions are welcome or b) slightly harder issues.

* `👋 good first issue`
* `🙏 help wanted`

**Comment by ChristianMurphy** [comment]
GitHub has special handling for the "help wanted" label
![Screenshot_2019-08-07 Apereo uPortal project contrib](https://user-images.githubusercontent.com/3107513/62627542-6d72c780-b8de-11e9-9def-489fe1f9d8c8.png)

Does adding an emoji in front impact the `(# issues need help)` messaging?

**Comment by wooorm** [comment]
@ChristianMurphy That’s a very good question! I searched for “React” and looked at what GitHub shows when you click that link:

- GitHub detects what labels you have. If you have `help wanted`, it’ll pick that. If you have `good first issue`, it’ll use that. It prefers `help wanted`.
- If you have such a label, it links to a search: `label:"help wanted" is:issue is:open`, and that count is shown everywhere
- It’s case insensitive, `Help wanted` also works
- It supports emoji, and transforms them back into gemoji (when possible?! not all emoji have an available gemoji shortcode):
  https://github.com/infinitered/reactotron/issues?q=label%3A%22help+wanted+%3Awave%3A%22+is%3Aissue+is%3Aopen

**Comment by johno** [comment]
Yay! Thanks for taking this on, I've been wanting this for a while!

I'd like to propose also adding some sort of "awaiting response" (`🧘‍♀️ status/waiting` or something) label which indicates an issue has been initially triaged but requires additional information or a reproduction.

It'd be cool to also keep the label colors consistent across repos, too (IMO).

**Comment by wooorm** [comment]
Waiting: I like the idea of that, could you confirm if my thinking matches yours?
`status/waiting` is applied (and `status/open` removed) when there’s an initial response from a maintainer and it may go somewhere, but the complete picture isn’t really there yet. The issue (or its solution) aren’t confirmed yet?

Colors: Yes!! Do you have a nice cooler scheme we can use? I’m thinking one colour per group, and slightly rotated hue or more/less lightness per label in the group?

**Comment by johno** [comment]
> Waiting: I like the idea of that, could you confirm if my thinking matches yours?
status/waiting is applied (and status/open removed) when there’s an initial response from a maintainer and it may go somewhere, but the complete picture isn’t really there yet. The issue (or its solution) aren’t confirmed yet?

Yeah, exactly what I was thinking.

> Colors: Yes!! Do you have a nice cooler scheme we can use? I’m thinking one colour per group, and slightly rotated hue or more/less lightness per label in the group?

I don't have a color scheme on the top of my head right now, but yeah it'd be rad to rotate colors slightly in each group.

**Comment by ChristianMurphy** [comment]
> [is there a] nice [color] scheme we can use?

Maybe use the same color palette as the unified project logos use?

**Comment by wooorm** [comment]
How about this? https://github.com/unifiedjs/github-tools/labels?page=1&sort=name-asc This uses org colours and adjusts the lightness. Note that there are a lot of `area`s (and statusses), so they had to be more similar to each other than the other groups.

~~We also kinda have one label too many 😅 GH shows only 30 per page, we have 31.~~ This is a lot of labels. About 33. Do we need them all?

Alternatives: adjust hue slightly (5deg?)

**Comment by ChristianMurphy** [comment]
> This is a lot of labels. About 33. Do we need them all?

I think 33 overall labels is fine. :man_shrugging: 
Only 5 or so will be applied to each PR, and with prefixing they should be pretty easy to find.

**Comment by johno** [comment]
Love it!

Oh, one other thing, on MDX I use an "rfc" label in place of maintaining an RFC repo since they're few and far between. I dunno if that fits in here or not, since it seems slightly different that "discussion" 🤔

**Comment by wooorm** [comment]
@johno Please check your usage and whether it matches this proposal, could definitely be something missing!

I had `type/discussion` and `type/rfc` in here, and I opted to keep only the first because it’s broader, so it may be used for more things, and it’s not an acronym (RFC may be unknown to people).

Don’t have strong feelings though!

**Comment by johno** [comment]
Yeah I'm cool to run with `type/discussion` for now and can open up an issue later if I find it doesn't seem to be working so we can revisit 👍

**Comment by wooorm** [comment]
So I found that `🙏 help wanted` does not work (neither does `:pray: help wanted`). GH seems to accept other stuff only at the end (like emoji, gemoji), as in, there’s something like a`/^help[ -]wanted/` regex.

I’m going with emoji at the end in `good first issue` and `help wanted`!
