### ISSUE TITLE
Consider new colors with higher contrast for GitHub labels

### ISSUE THREAD

**Issue by johno** [unifiedjs/github-tools#9]
AFAICT this is more brought to light recently with the latest GH design changes because it appears the typography of the labels has changed a bit making it harder to read. The label colors themselves seem to be a bit too saturated despite the fact that contrast ratio is AAA.

The contrast for the pink/fuschia color:

```
❯ npx get-contrast #fd5efd #000
npx: installed 12 in 1.312s
Ratio: 8.195980582476533
Score: AAA
```

This is saturation issue quite apparent on some types of monitors. Here's a screenshot from a colleague:

![image](https://user-images.githubusercontent.com/1424573/86965296-8c985b80-c124-11ea-91c0-17c8faabac36.png)

It appears more clear and legible on my screen:

![image](https://user-images.githubusercontent.com/1424573/86965544-fa448780-c124-11ea-853a-b5fcbfb60f33.png)

I think it'd be pertinent to explore some colors that appear less saturated on screens to ensure they're as legible as possible.

**Comment by wooorm** [comment]
- The colors in use can be browsed here: https://github.com/unifiedjs/github-tools/labels
- Gradients are defined here: https://github.com/unifiedjs/github-tools/blob/main/config/github-labels.yml. I believe changing them there would bubble it through the ecosystem.

Is the bug that the black is hard to read on the colored background (I think that’s what I’m reading), or that the lighter backgrounds blend in too much with the white background?

> despite the fact that contrast ratio is AAA

Yeah, I believe GH analyzes the background color and switches the foreground text to either white or black to get a correct contrast.

**Comment by wooorm** [comment]
@laurieontech could you confirm whether this looks okay on your screen? https://github.com/unifiedjs/unified/labels

**Comment by laurieontech** [comment]
@wooorm much better!

**Comment by wooorm** [comment]
Perfect, I’ll close this then! Do let me know if you have further suggestions regarding labels and colours!
